### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by changeave** [lllyasviel/style2paints#11]
python server.py

Using TensorFlow backend.
Traceback (most recent call last):
  File "server.py", line 178, in <module>
    chainer.serializers.load_npz('google_net.net', google_net)
  File "/usr/local/lib/python2.7/dist-packages/chainer/serializers/npz.py", line 132, in load_npz
    with numpy.load(filename) as f:
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'google_net.net'

**Comment by abbychau** [comment]
Model

Models are avaliable in 'release' page.

base_generator.net all rights reserved 2017 style2paints
paintschainer.net from paintschainer
google_net.net from nico-opendata

**Comment by abbychau** [comment]
The models are updating and it will be able to be downloaded soon.

**Comment by lllyasviel** [comment]
Update finished. Models are avaliable now.
Closed.
