### ISSUE TITLE
unable to open file 

### ISSUE THREAD

**Issue by jf3096** [lllyasviel/style2paints#124]
```bash
D:\projects\style2paints-master\V3\server>python server.py
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0808 14:13:32.818989 18680 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0808 14:13:32.818989 18680 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0808 14:13:32.819990 18680 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:186: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-08-08 14:13:32.838214: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-08-08 14:13:32.853148: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-08-08 14:13:33.005478: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.392
pciBusID: 0000:01:00.0
2019-08-08 14:13:33.020474: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-08-08 14:13:33.029147: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-08 14:13:33.793880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-08 14:13:33.803764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-08-08 14:13:33.807418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-08-08 14:13:33.813186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3000 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
W0808 14:13:33.829989 18680 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:190: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

W0808 14:13:33.830989 18680 deprecation_wrapper.py:119] From D:\projects\style2paints-master\V3\server\ai.py:44: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "server.py", line 16, in <module>
    from ai import *
  File "D:\projects\style2paints-master\V3\server\ai.py", line 50, in <module>
    baby = load_model('baby.net')
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 19215124, sblock->base_addr = 0, stored_eof = 74749848)
```

**Comment by 5grs** [comment]
Have you solved the problem？

**Comment by gceboh** [comment]
It seems that the downloaded model file `baby.net` is corrupt，please download it again.
