### ISSUE TITLE
Dst tensor is not initialized, How can I do?

### ISSUE THREAD

**Issue by MuQQQQQ** [lllyasviel/style2paints#130]
I have installed everything, but When I run the server.py, a lot of warnings and errors occurred.
below is the output:

_WARNING:tensorflow:From C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

Warning (from warnings module):
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\saving.py", line 341
    warnings.warn('No training configuration found in save file: '
UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
**tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Dst tensor is not initialized.
	 [[{{node _arg_Placeholder_829_0_140}}]]
	 [[ReadVariableOp_839/_5087]]
  (1) Internal: Dst tensor is not initialized.
	 [[{{node _arg_Placeholder_829_0_140}}]]**
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\s2p\style2paints\V3\server\server.py", line 18, in <module>
    from ai import *
  File "E:\s2p\style2paints\V3\server\ai.py", line 79, in <module>
    neck = load_model('neck.net')
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\saving.py", line 336, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\backend\tensorflow_backend.py", line 2960, in batch_set_value
    tf_keras_backend.batch_set_value(tuples)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3363, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\mi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Dst tensor is not initialized.
	 [[{{node _arg_Placeholder_829_0_140}}]]
	 [[ReadVariableOp_839/_5087]]
  (1) Internal: Dst tensor is not initialized.
	 [[{{node _arg_Placeholder_829_0_140}}]]
0 successful operations.
0 derived errors ignored._

**Comment by viet1pro** [comment]
You run it with CPU or GPU?

**Comment by MuQQQQQ** [comment]
> What do you run it with? CPU or GPU?
Oh, thanks for your reply,
After add `os.environ['CUDA_VISIBLE_DEVICES']='1'`, I sucessfully run the server, although I don't know why it can work...
