### ISSUE TITLE
RuntimeError: `get_session` is not available when using TensorFlow 2.0.

### ISSUE THREAD

**Issue by sw112874** [lllyasviel/style2paints#133]
While trying to run style2paints, I get this error:

C:\Users\-\style2paints\V3\server>python server.py
2019-12-07 16:13:36.430100: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Using TensorFlow backend.
Traceback (most recent call last):
  File "server.py", line 16, in <module>
    from ai import *
  File "C:\Users\-\style2paints\V3\server\ai.py", line 39, in <module>
    session = keras.backend.get_session()
  File "C:\Users\-\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 379, in get_session
    **'`get_session` is not available '**
**RuntimeError: `get_session` is not available when using TensorFlow 2.0.**

**Comment by Oskop** [comment]
You must use tensorflow 1.x.x instead of tensorflow 2.x.x. If you insist on
using tensorflow ver 2.x.x, you can rewrite the import script from "import
tensorflow as tf" into "import tensorflow.compat.v1 as tf"

Pada tanggal Min, 8 Des 2019 05.29, sw112874 <notifications@github.com>
menulis:

**Comment by gceboh** [comment]
[[Instruction] Run style2paints v3 offline](https://github.com/lllyasviel/style2paints/issues/100)

https://raw.githubusercontent.com/SNSLogty/style2paints_v3_launcher/master/requirement_cpu.txt
`tensorflow==1.10.0
...
`
