### ISSUE TITLE
Failed to execute script Style2PaintsV45: TensorFlow binary was not compiled, CUDA errors

### ISSUE THREAD

**Issue by yupzhou** [lllyasviel/style2paints#135]
While trying to run style2paints, I get this error:

Port is ready for usage.
Style2Paints Customed Tensorflow Shifting to GPU.
Style2Paints V45 Start Loading. V20191214.
Numpy: 1.15.0
Opencv: 4.1.2
Tensorflow: 1.4.0
2020-02-06 10:08:59.430421: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-02-06 10:09:00.670786: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_UNKNOWN
Traceback (most recent call last):
  File "Style2PaintsV45.py", line 595, in <module>
  File "Style2PaintsV45.py", line 196, in main_exec
  File "site-packages\tensorflow\python\client\session.py", line 1482, in __init__
  File "site-packages\tensorflow\python\client\session.py", line 622, in __init__
  File "site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
[6076] Failed to execute script Style2PaintsV45

**Comment by freezeLUO** [comment]
I have the same problem,gtx 1060

**Comment by gceboh** [comment]
> Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_UNKNOWN

This error may be hard to solve. Maybe your Nvidia driver has some problems.


**[Workaround]**
Please try to use the "CPU mode" instead.
Select `I do not have Nvidia GPU or I use AMD GPU`, when you launch `style2paints.exe`. The colorization process will be slower.
