### ISSUE TITLE
Error if the sketch is not reloaded before every colorization

### ISSUE THREAD

**Issue by CorentinJ** [lllyasviel/style2paints#17]
If I press "colorize" without having loaded a new sketch, I get this python error in the console:

```
127.0.0.1 - - [2017-09-27 14:22:48] "GET /results/Sep_27_14_22_42__658.jpg?t=0.5077750082463517 HTTP/1.1" 200 49476
0.003000
received
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "E:\Python35\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "server.py", line 258, in do_paint
    raw_sketch = from_png_to_jpg(sketchDataURL)
  File "server.py", line 395, in from_png_to_jpg
    color = map[:, :, 0:3].astype(np.float) / 255.0
TypeError: 'NoneType' object is not subscriptable
```

**Comment by lllyasviel** [comment]
can you give me some more detailed description? Thanks

**Comment by lllyasviel** [comment]
fixed
