### ISSUE TITLE
When will style2paints support M1 mac?

### ISSUE THREAD

**Issue by Jin-cpp** [lllyasviel/style2paints#198]
I successfully installed all the dependencies but still falled to run the style2paints. I got error:
`Traceback (most recent call last):
  File "/Users/jin_cpp/GitHub/style2paints/V4.5/s2p_v45_server/Style2PaintsV45_source.py", line 233, in <module>
    tail_op_g, head_op_g, render_op_g, refs_img_g = make_graph()
  File "/Users/jin_cpp/GitHub/style2paints/V4.5/s2p_v45_server/Style2PaintsV45_source.py", line 199, in make_graph
    features = reader(ip3 / 255.0)
  File "/Users/jin_cpp/mambaforge/envs/tf26/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/jin_cpp/mambaforge/envs/tf26/lib/python3.9/site-packages/keras/engine/input_spec.py", line 295, in assert_input_compatibility
    raise ValueError(
ValueError: Input 0 of layer "model_1" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(None, 128, 128, 3)`

**Comment by Ihateyoudattebayo** [comment]
It only supports windows, however project SEPA(releasing at the same time as GTA 6) will support mac.

**Comment by slashdottir** [comment]
what is project SEPA please? Thanks for any info
