### ISSUE TITLE
Error running v4.5 on Colab

### ISSUE THREAD

**Issue by sulaimangari** [lllyasviel/style2paints#199]
```shell
Traceback (most recent call last):
  File "style2paints/V4.5/s2p_v45_server/Style2PaintsV45_source.py", line 231, in <module>
    tail_op_g, head_op_g, render_op_g, refs_img_g = make_graph()
  File "style2paints/V4.5/s2p_v45_server/Style2PaintsV45_source.py", line 197, in make_graph
    features = reader(ip3 / 255.0)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/input_spec.py", line 295, in assert_input_compatibility
    raise ValueError(
ValueError: Input 0 of layer "model_1" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(None, 128, 128, 3)
```

Keep returning error. Colab doesn't support tf1 so I running this on tf2.
I assumed this code compatible with tf2 because this exist on source code: 

```python 
import tensorflow

tensorflow.compat.v1.disable_v2_behavior()
tf = tensorflow.compat.v1
```
Help is appreciated, thanks.

**Comment by qingxian233** [comment]
您好(*?0?7▽｀)ノノ青弦已经收到您的邮件啦！请耐心等待，10个工作日内会给您回复w

**Comment by xinyeCH** [comment]
@sulaimangari Hello, I have the same problem, can I ask that how did you solve it?

**Comment by AkTheBoss001** [comment]
Can u provide the colab link??

**Comment by sulaimangari** [comment]
I end up using v4.0, it looks like the dev just focused on the new released with UI now.

**Comment by AkTheBoss001** [comment]
> I end up using v4.0, it looks like the dev just focused on the new released with UI now.

Please can you provide colab link?

**Comment by Flashbaurger888888** [comment]
Same for me.
colab link: https://colab.research.google.com/drive/12jJn9cEVeDLGwA9bSjq4jV82AaaiG26G?usp=sharing

**Comment by 03stevensmi** [comment]
If it helps anyone:
https://highcwu-style2paints-4-5-gradio.hf.space/file/ui/web-mobile/index.html
https://huggingface.co/spaces/HighCWu/Style2Paints-4.5-Gradio

**Comment by AkTheBoss001** [comment]
> If it helps anyone:
> https://highcwu-style2paints-4-5-gradio.hf.space/file/ui/web-mobile/index.html
> https://huggingface.co/spaces/HighCWu/Style2Paints-4.5-Gradio

Bro thanks,this is a big help. I will try it soon. 😊 thanks

**Comment by 03stevensmi** [comment]
> > If it helps anyone:
> > https://highcwu-style2paints-4-5-gradio.hf.space/file/ui/web-mobile/index.html
> > https://huggingface.co/spaces/HighCWu/Style2Paints-4.5-Gradio
> 
> Bro thanks,this is a big help. I will try it soon. 😊 thanks

Lol no problem bro. Enjoy! :)

**Comment by DiCeYMaYo** [comment]
> If it helps anyone: https://highcwu-style2paints-4-5-gradio.hf.space/file/ui/web-mobile/index.html https://huggingface.co/spaces/HighCWu/Style2Paints-4.5-Gradio

brother could you update the link, I'm completely fed up trying to run this inside Collab
