### ISSUE TITLE
Windows Bash

### ISSUE THREAD

**Issue by rocketinventor** [lllyasviel/style2paints#31]
Hi, I was following the instructions on the Readme to get the server running (on Windows Bash). When I tried running `python server.py` I just got the following error...
All Python packages are up to date.

```
Traceback (most recent call last):
  File "server.py", line 14, in <module>
    import cv2
  File "/home/ResT_n/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/ResT_n/.local/lib/python2.7/site-packages/cv2/__init__.py", line 9, in <module>
    from .cv2 import *
  File "/home/ResT_n/.local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```

**Comment by abbychau** [comment]
you need a python 3 environment.

**Comment by rocketinventor** [comment]
I tried using `python3 server.py` to get a Python 3 environment.

I got different errors this time...

```
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    from gevent import monkey; monkey.patch_all()
ImportError: No module named 'gevent'
```

**Comment by abbychau** [comment]
you have to install bottle and gevent under python3.
or if you are not familiar with python. you can uninstall your current version and download the latest version again.
