### ISSUE TITLE
load_model Error

### ISSUE THREAD

**Issue by Joshua1023** [lllyasviel/style2paints#93]
Some error happened when loading the models:
Has anyone met similar problem and how to solve it?  
> Traceback (most recent call last):
  File "server.py", line 16, in <module>
    from ai import *
  File "/home/luhuajin/server/ai.py", line 50, in <module>
    baby = load_model('baby.net')
  File "/home/luhuajin/anaconda3/envs/tf/lib/python3.5/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/luhuajin/anaconda3/envs/tf/lib/python3.5/site-packages/keras/engine/saving.py", line 249, in _deserialize_model
    layer_weights = model_weights_group[name]
  File "/home/luhuajin/anaconda3/envs/tf/lib/python3.5/site-packages/keras/utils/io_utils.py", line 283, in __ getitem __
    val = self.data[attr]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/luhuajin/anaconda3/envs/tf/lib/python3.5/site-packages/h5py/_hl/group.py", line 177, in __ getitem __
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (bad object header version number)'

**Comment by SNSLogty** [comment]
Try python 3.6.7 [Download](https://www.python.org/downloads/release/python-367/)

**Comment by shiditime** [comment]
'baby.net'  是个啥玩意

**Comment by siddupp** [comment]
> Some error happened when loading the models: Has anyone met similar problem and how to solve it?
> 
> > Traceback (most recent call last):
> > File "server.py", line 16, in 
> > from ai import *
> > File "/home/luhuajin/server/ai.py", line 50, in 
> > baby = load_model('baby.net')
> > File "/home/luhuajin/anaconda3/envs/tf/lib/python3.5/site-packages/keras/engine/saving.py", line 419, in load_model
> > model = _deserialize_model(f, custom_objects, compile)
> > File "/home/luhuajin/anaconda3/envs/tf/lib/python3.5/site-packages/keras/engine/saving.py", line 249, in _deserialize_model
> > layer_weights = model_weights_group[name]
> > File "/home/luhuajin/anaconda3/envs/tf/lib/python3.5/site-packages/keras/utils/io_utils.py", line 283, in __ getitem __
> > val = self.data[attr]
> > File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> > File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> > File "/home/luhuajin/anaconda3/envs/tf/lib/python3.5/site-packages/h5py/_hl/group.py", line 177, in __ getitem __
> > oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
> > File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> > File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> > File "h5py/h5o.pyx", line 190, in h5py.h5o.open
> > KeyError: 'Unable to open object (bad object header version number)'

Do you got the answer?

**Comment by qingxian233** [comment]
您好(*?0?7▽｀)ノノ青弦已经收到您的邮件啦！请耐心等待，10个工作日内会给您回复w

**Comment by siddupp** [comment]
Thank you
